<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="xxx_chasis">
    <xacro:include filename="$(find xxx_description)/urdf/xxx_properties.xacro"/>
    <!-- include more files here-->
    <xacro:macro name="chassis" params="">
        <link name="base_footprint"/>
        <link name="base_link">
            <inertial>
                <origin xyz="${BASE_COM}"/>
                <mass value="${BASE_M}"/>
                <inertia 
                    ixx="${BASE_Ixx}" 
                    ixy="${BASE_Ixy}" 
                    ixz="${BASE_Ixz}" 
                    iyy="${BASE_Iyy}" 
                    iyz="${BASE_Iyz}" 
                    izz="${BASE_Izz}"/>
            </inertial>
            <visual>
                <origin xyz="0 0 -${BASE_MESH_Z_OFFSET}" rpy="0 0 ${PI/2}"/>
                <geometry>
                    <!-- add geometry here -->
                </geometry>
                <material name="chassis_color">
                    <color rgba="${BASE_COLOR}"/>
                </material>
            </visual>
            <collision>
                <geometry>
                    <box size="${BASE_LENGTH} ${BASE_WIDTH} ${BASE_HEIGHT}"/>
                </geometry>
            </collision>
        </link>
        <joint name="base_footprint_to_base_link" type="fixed">
            <parent link="base_footprint"/>
            <child link="base_link"/>
            <origin xyz="0.0 0.0 ${BASE_HEIGHT/2+BASE_ELEVATION}"/>
        </joint>
    </xacro:macro>
</robot>